background #202020
foreground #fcfcfa

cursor #fcfcfa
cursor_text_color #000000
selection_foreground #403e41
selection_background #fcfcfa

# 40m (dark gray)
color0 #403e41
color8 #727072

# 41m (red)
color1 #ff6188
color9 #ff6188

# 42m (green)
color2 #a9dc76
color10 #a9dc76

# 43m (yellow)
color3 #ffd866
color11 #ffd866

# 44m (blue)
color4 #456ed6
color12 #456ed6

# 45m (purple)
color5 #ab9df2
color13 #ab9df2

# 46m (cyan)
color6 #1fa6c2
color14 #1fa6c2

# 47m (white)
color7 #fcfcfa
color15 #fcfcfa

