# vim:fileencoding=utf-8:foldmethod=marker

# In order to make this config file less longer I organize
# all configs into separate files. Then, the stock kitty conf
# is still available in those files, but my personal settings
# are just in the followings includes

### My personal config files

include ./settings/fonts.conf
include ./settings/cursor.conf
include ./settings/tab_bar.conf

include ./themes/elio.conf

# This file is ignored with git. Is to use custom settings for
# each PC.
include ./custom_settings.conf
